### ISSUE TITLE
Additional FS

### ISSUE THREAD

**Issue by purpleidea** [twpayne/go-vfs#14]
Hey! Nice work... Golang really needs a standard Filesystem interface upstream, or at least one that everyone gathers around. In any case, maybe my etcdfs work is helpful here. I'm not contributing to afero anymore because: https://github.com/spf13/afero/pull/184

I saw your compatibility layer in https://github.com/twpayne/go-vfsafero -- it would be interesting to be able to go the other way!

In any case, feel free to close this, thought it might be a good place for discussing additional FS.

**Comment by purpleidea** [comment]
EtcdFs code is here btw: https://github.com/purpleidea/mgmt/tree/master/etcd/fs

**Comment by twpayne** [comment]
Thanks for opening the issue!

The simplest way to achieve this is for EtcdFs to implement the [`vfs.Fs` interface](https://godoc.org/github.com/twpayne/go-vfs#FS), which will allow EtcdFs to be used directly.

I tried a few times to build `mgmt` to test if EtcdFs already implemented `vfs.Fs`, but was unsuccessful (nested `vendor` directories, missing dependencies, running `make deps` tried to write to my root filesystem, ...). Please tell me if you'd like a full report.

Closing this issue in the meantime.

**Comment by purpleidea** [comment]
> I tried a few times to build mgmt to test if EtcdFs already implemented vfs.Fs, but was unsuccessful

You can just import the etcd fs package instead of building the whole thing.

 (nested vendor directories, 

We just use git submodules. If you `git clone --recursive` as in the https://github.com/purpleidea/mgmt/blob/master/docs/quick-start-guide.md it should just work. If not, please let us know where!

> missing dependencies

Can you file a bug or let me know what here?

running make deps tried to write to my root filesystem

Hmm... Well it does run `dnf` and `apt`, all the code is in the repo. If you think there's something wrong or suspicious, please let us know where!

, ...). Please tell me if you'd like a full report.

Yes please! Thanks

**Comment by purpleidea** [comment]
> OK, I did something - I'm not sure what - to my system and now mgmt builds. Apologies for the lack of clarity, I'll try to write a better report if I have the time.

Sweet! Happy to help in #mgmtconfig on Freenode IRC or you can open an issue.

> Note that I'm on macOS at the moment so apt and friends don't work.

I develop and test on Linux, but I know of a non-zero number of people who have tried it on OSX. Having said that, if we're doing something wrong, patches are certainly welcome. obviously the systemd parts won't work on OSX, but there is nothing blocking equivalent resources if someone wants them.

> In this case, Chown and Lchown need to be implemented for github.com/purpleidea/mgmt/etcd/fs.Fs

Sweet... Are all the signatures the same across all the different vfs'? I'd mostly just like one vfs for golang. If this is it, awesome.

I don't have a uid/gid field in the file at the moment, but would love to add it, time permitting: https://github.com/purpleidea/mgmt/blob/d0b5c4de68d967985ce2cb35ac4145e7b5c623e0/etcd/fs/file.go#L42 (patches welcome!)

I guess my point about opening up this issue was to give you a heads up about an fs implementation that I'm maintaining for now, and maybe we get everyone together around one project and an upstream interface type.

**Comment by twpayne** [comment]
> Sweet... Are all the signatures the same across all the different vfs'? I'd mostly just like one vfs for golang. If this is it, awesome.

Yes, it's [`os.Chown`](https://godoc.org/os#Chown) and [`os.Lchown`](https://godoc.org/os#Lchown) are the same across all vfs's - they just follow the Go standard library here. Of course, although the standard library call is available everywhere, it doesn't mean that they also has the same runtime behavior everywhere ;)

In the short term, for `github.com/purpleidea/etcd/fs.Chown` I'd suggest just returning `errors.New("not implemented")` which is enough to satisfy the interface and provide debuggable behavior for developers.

**Comment by twpayne** [comment]
See https://github.com/purpleidea/mgmt/pull/428 for the commit points :)

> Yeah, so I wondered about this, particularly when implementing my FS.
If there's a standard test suite we could all run against, I'd really
appreciate it.

I'm pretty sure that there is no standard, as the behavior varies from filesystem to filesystem. Trivial examples are case sensitivity, case preserving-ness (is that even a word?), existence or otherwise of symlinks, hardlinks, and other special files, and whether you can delete a file opened by another process. I think the best you can do for `github.com/purpleidea/mgmt/etcd/fs.Fs` is say "this behaves like filesystem X" for some value of X (e.g ext2, xfs, btrfs, zfs, fat32, ntfs, or whatever) but there is no standard behavior for general filesystems.

**Comment by twpayne** [comment]
Fixed in https://github.com/purpleidea/mgmt/pull/428.

**Comment by purpleidea** [comment]
Random thought: do you want to add another test like this: https://github.com/purpleidea/mgmt/pull/428/commits/166103f496085d8051e234485fabd9ed8e9cc419 so that we implement your vfs as well?

Secondly: do you want a "list of available filesystems that implement go-vfs" on your README? If so, LMK, I can send a patch.

**Comment by twpayne** [comment]
> Random thought: do you want to add another test like this: purpleidea/mgmt@166103f so that we implement your vfs as well?

Nice idea, but you have to choose either `afero.Fs` or `vfs.FS` because of the different signatures of methods returning files. For example, `afero.Fs.Create` returns an `afero.File`, whereas `vfs.FS.Create` returns an `*os.File`. As it currently stands, `purpleidea/mgmt/etcd/fs.Fs.Create` returns an `afero.File`, and is compatible with `vfs.FS` through [`github.com/twpayne/go-vfsafero`](https://github.com/twpayne/go-vfsafero):

> Secondly: do you want a "list of available filesystems that implement go-vfs" on your README? If so, LMK, I can send a patch.

Sure, but at the moment they're just in the `vfs` package itself.
